export const LOADING_STARTED = 'LOADING_STARTED';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const LOADING_ENDED = 'LOADING_ENDED';
export const LOADING_ERROR = 'LOADING_ERROR';
export const UPDATE_ARRANGED_PRODUCTS = 'UPDATE_ARRANGED_PRODUCTS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const UPDATE_SORTBY = 'UPDATE_SORTBY';